config/routes.rb
Rails.application.routes.draw do
  get 'entries/new'
  get 'entries/create'
  get 'places/index'
  get 'places/show'
  get 'places/new'
  get 'places/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # get("/", { :controller => "articles", :action => "index" })

  resources :places do
    resources :entries, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :entries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_place

  def new
    @entry = @place.entries.new
  end

  def create
    @entry = @place.entries.new(entry_params)
    if @entry.save
      redirect_to place_path(@place)
    else
      render :new
    end
  end

  private

  def set_place
    @place = Place.find(params[:place_id])
  end

  def entry_params
    params.require(:entry).permit(:title, :description, :posted_on)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
  end

  def show
    @place   = Place.find(params[:id])
    @entries = @place.entries
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to @place
    else
      render :new
    end
  end

  private

  def place_params
    params.require(:place).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/create.html.erb
<h1>Entries#create</h1>
<p>Find me in app/views/entries/create.html.erb</p>

app/views/entries/new.html.erb
<h1>New Post for <%= @place.name %></h1>

<%= form_with model: [@place, @entry], local: true do |f| %>
  <div>
    <%= f.label :title, "Title" %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description, "Description" %><br>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :posted_on, "Date" %><br>
    <%= f.date_field :posted_on %>
  </div>

  <div>
    <%= f.submit "Create Post" %>
  </div>
<% end %>

<p>
  <%= link_to "← Back to #{@place.name}", place_path(@place) %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StarterApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/create.html.erb
<h1>Places#create</h1>
<p>Find me in app/views/places/create.html.erb</p>

app/views/places/index.html.erb
<h1>Places I’ve Been</h1>

<ul>
  <% @places.each do |place| %>
    <li>
      <%= link_to place.name, place_path(place) %>
    </li>
  <% end %>
</ul>

<%= link_to "New Place", new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= form_with model: @place, local: true do |f| %>
  <div>
    <%= f.label :name, "Place Name" %><br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.submit "Create Place" %>
  </div>
<% end %>

<p>
  <%= link_to "← Back to Places", places_path %>
</p>

app/views/places/show.html.erb
<h1><%= @place.name %></h1>

<p>
  <%= link_to "← Back to Places", places_path %>
</p>

<% if @entries.any? %>
  <% @entries.each do |entry| %>
    <div class="entry">
      <h2><%= entry.title %></h2>
      <small><%= entry.posted_on %></small>
      <p><%= entry.description %></p>
    </div>
    <hr>
  <% end %>
<% else %>
  <p>No entries yet.</p>
<% end %>

<p>
  <%= link_to "New Post", new_place_entry_path(@place) %>
</p>